[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gmail-invoice-agent"
version = "0.1.0"
dependencies = [
    "pandas"
]

[tool.setuptools.packages.find]
where = ["."]
